# Generated by Django 3.0.6 on 2020-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('file', models.FileField(upload_to='price_file/')),
            ],
            options={
                'verbose_name': 'Price файл',
                'verbose_name_plural': 'Price файлы',
                'ordering': ['name'],
            },
        ),
    ]
