# Generated by Django 3.0.6 on 2020-05-14 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.CharField(max_length=60, verbose_name='Парт номер')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('price_name', models.CharField(max_length=60, verbose_name='Название прайса')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.AddField(
            model_name='pricefile',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricefile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pricefile',
            name='log',
            field=models.TextField(blank=True, default='', help_text='ошибки, сообщения, отладочная информация', verbose_name='Лог'),
        ),
        migrations.AddField(
            model_name='pricefile',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Загружен'), (1, 'В очереди на обработку'), (2, 'В процессе обработки'), (3, 'Обработан')], default=0, verbose_name='Статус'),
        ),
    ]
