# Generated by Django 3.0.6 on 2020-05-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20200514_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricefile',
            name='params',
            field=models.TextField(blank=True, default='', help_text='JSON объект. Значения для парсинга', verbose_name='Параметры'),
        ),
    ]
